TRANSLATIONS = {
    "uz": {
        "start": "Assalomu alaykum! Nima qilamiz?",
        #mustaqil ish yozish
        "university_mustaqil": "Universitetingizni kiriting:",
        "student_mustaqil": "Talaba ismingizni kiriting:",
        "student_tezis": "Yozuvchining ism familiyasini kiriting. (F.I.SH)",
        "teacher_mustaqil": "Qabul qiluvchini kiriting:",
        "topic_mustaqil": "Mavzu:",
        "pages_mustaqil": "Mustaqil ish nechi sahifadan iborat bo'lishi kerak?",
        "mustaqil_generating": "Mustaqil ish tayyorlanmoqa iltimos biroz kuting...",
        "caption_mustaqil": "Bu sizning Mustaqil ishingiz. Iltimos ko‘z tashlab chiqing. \n @slayd_chibot - slayd, referat tayyorlovchi!",
        "language": "Tilni tanlang:",
        "menu_alert": "Iltimos Botdan menyu orqali foydalaning",
        "menu_back": "⬅️ Orqaga",
        "menu_word_save": "💾 Saqlash",
        "caption_file": "Tayyor!\nTizim xato qilishi mumkin iltimos muhim malumotlarni tekshiring.",
       #mustaqil ishi va referat yuzi
       "mustaqil_ishi_titul": "MUSTAQIL ISH",
       "bajaruvchi_titul": "Bajardi:",
       "qabul_qiluvchi_titul": "Qabul qildi:",
       "xulosa_titul": "Xulosa",
       "adabiyotlar_titul": "Foydalanilgan Adabiyotlar",
        "mavzu_titul": "Mavzu",
        "Referat_titul": "REFERAT",
        "reja_titul": "REJA:",

        "alert_upcoming": "Bu menyu tez orada ishga tuishadi..",
        "tezis_generating":"Tezisingiz tayyorlanmoqa iltimos biroz kuting...",
        "payment_manual": "1.To‘lovni istalgan to‘lov tizimi orqali quyidagi plastik kartaga tanlagan miqdoringizni o‘tkazing.\n\n-Karta raqami: 9860340103696845\n-Karta egasi: Azamjon Roziboyev\n\n2.So‘ngra to‘lov chekini screenshot yoki PDF shaklida yuboring.\n3.To‘lovingiz tasdiqlanishini kuting. Bu jarayon taxminan 5 daqiqa vaqt olishi mumkin.",
        #menu buttons
        "menu_referat": "📄 Referat yaratish",
        "menu_presentation": "📊 Prezentatsiya",
        "menu_word": "📝 Word fayl yaratish",
        "menu_help": "ℹ️ Yordam",
        "menu_tezis": "✍️ Tezis yozish",
        "menu_mustaqil": "📜 Mustaqil ish yozish",
        "balance_info": "Sizning balansingiz:",
        "menu_balance": "💰Balans",
        #referat yozish
        "university_referat": "Universitetingizni kiriting:",
        "student_referat": "Ismingizni kiriting:",
        "language_referat": "Referat qaysi tilda bo'lsin.",
        "language_tezis": "Tezis qaysi tilda bo'lsin.",
        "teacher_referat": "Qabul qiluvchini kiriting:",
        "topic_referat": "Mavzu:",
        "pages_referat": "Referat nechi sahifadan iborat bo'lishi kerak?",
        "referat_generating": "Referatingiz tayyorlanmoqa iltimos biroz kuting...",
        "language_mustaqil": "Mustaqil ish qaysi tilda bo'lsin:",
        "alerta_payment": "❌ Sizda bepul urinishlari qolmagan va balans yetarli emas.💳 Iltimos, balansingizni to'ldiring.",
        "menu_referal": "🆓 Bepul yaratish",
        "menu_prices": "🏷️ Narxlar",
        "make_payment" : "Hisobni to'ldirish 💲",
        "choose_amount" : "Hiosbingizni qanchaga to'ldirmoqchisiz? \n\n iltimos quyidagi miqdorlardan birini tanlang:",
        "send_receipt": "📸Iltimos, to‘lov chek rasmi yoki pdf faylini yuboring:\n\nIltimos to'lov checkida to'lov vaqti mavjudligiga etibor bering!\n\n To'lov vaqti mavjud bo'lmaqan checklar qabul qilinmaydi!",
        "welcome": "👋 Xush kelibsiz!\n\nBotni ishga tushirish orqali siz quyidagi bepul urinishlarni qo‘lga kiritdingiz:\n\n📄 Referat yaratish — 2 ta bepul urinish\n📊 Prezentatsiya yaratish — 2 ta bepul urinish\n📝 Tezis tayyorlash — 2 ta bepul urinish\n📚 Mustaqil ish yaratish — 2 ta bepul urinish\n\nHar bir xizmatdan bepul foydalanish huquqi mavjud.\nBepul urinishlar tugagach, xizmatlardan foydalanish uchun balansingiz bo‘lishi kerak bo‘ladi 💰\n\n📌 Bundan tashqari, do‘stlaringizni botga taklif qilish orqali ham balansingizni to‘ldirishingiz mumkin.\nBuning uchun 🆓 Bepul yaratish menyusiga kiring.",
        "policy_confirmation": "\n Bundan tashqari shuni yodda tutingki. Botdan foydalanish orqali maxfiylik siyosatiga rozilik bildirgan bo'lasiz.\nMaxfiylik siyosati bilan pastdagi havola bilan tanishing.\nhttps://telegra.ph/SLAYD-CHI-TELEGRAM-BOT--MAXFIYLIK-SIYOSATI-12-19",       
       "referal_payment": "🎉 Sizning referalingiz botni ishga tushirdi!\n+1000 so‘m balansingizga qo‘shildi 💰",
        "help_menu_text" : "ℹ️ Yordam\n🤖 Ushbu bot o‘quv ishlarini tez va qulay tayyorlashga yordam beradi.\n📝 Word fayl yaratish menyusi yordamida siz istalgan matn va rasmlaringizni words fayliga joylashingiz mumkin. Yaratilgan fayld .docx fayli sifatida saqlanadi.\n📄 Referat — mavzu asosida referatni avtomatik tayyorlaydi, til va hajm tanlanadi.\n📊 Prezentatsiya — slaydlar ko‘rinishida prezentatsiya yaratadi, mavzu va slaydlar soni tanlanadi.\n🧾 Tezis — ilmiy tezis yoki qisqa xulosa matnini yaratadi.\n📝 Mustaqil ish — talabalar uchun mustaqil ish tayyorlaydi, mavzu va hajm tanlanadi.\n💰 Balans — balans va qolgan bepul urinishlarni ko‘rsatadi.\n🎁 Bepul urinishlar — do‘stlarni taklif qilib bepul urinishlarga ega bo‘ling.\n⚙️ Sozlamalar — til va bot sozlamalarini o‘zgartirish.\n📩 Aloqa — savollar va muammolar bo‘yicha admin bilan bog‘lanish.\n📌 Eslatma: botdan faqat menyu orqali foydalaning.",
        "payment_sent": "Check muvafaqiyatli yuborildi. \n To'lovingiz to'griligi tasdqilanishi bilanoq hisobingiz to'ldiriladi.Bu nari borsa 5 daqiqa vaqt olishi mumkin.\n Hisobingizni 💰Balans menyusi orqali tekshiring.",
        "text_prices": "💰 Xizmatlar narxlari\n📊 Prezentatsiya (taqdimot) yaratish — 3 000 so‘m\n📄 Referat yozish — 2 000 so‘m\n📘 Mustaqil ish tayyorlash — 2 000 so‘m\n📝 Tezis yozish — 3 000 so‘m\n\n💳 To‘lov balans menusi orqali amalga oshiriladi.\nℹ️ Balans yetarli bo‘lmasa, xizmatdan foydalanib bo‘lmaydi.",
        "payment_confirmed": "✅ Sizning  to'lovingiz tasdiqlandi.\nTo'lov miqdori:",
        "payment_rejected": "❌ Sizning  to'lovingiz rad etildi.",
        "payment_auto_refund": "✅ Sizning  to'lovingiz tasdiqlandi"

    },
    "ru": {
        "start": "Здравствуйте! Что делаем?",
        #mustaaqil ish
        "university_mustaqil": "Введите университет:",
        "student_mustaqil": "Введите имя студента:",
        "teacher_mustaqil": "Введите приемника:",
        "topic_mustaqil": "Тема:",
        "caption_file": "Готово!\nСистема может допускать ошибки, пожалуйста, проверьте важную информацию.",

        "student_tezis": "Введите имя, фамилию и отчество автора. (Ф.И.О.)",
        "pages_mustaqil": "Сколько страниц должен быть реферат?",
        "mustaaqil_generating": "Самостоятельная работа готовится, пожалуйста, подождите немного...",
        "language": "Выберите язык:",
        "language_tezis": "На каком языке будет тезис: ",
        "caption_mustaqil": "Это ваша самостоятельная работа. Пожалуйста, ознакомьтесь.\n @slayd_chibot - создатель слайдов и рефератов!",
        #menu buttons
        "menu_alert": "Пожалуйста, используйте бота через меню", #echo handler
        "alert_upcoming": "Это меню скоро начнёт работать.",
        "tezis_generating":"Ваша диссертация готовится, пожалуйста, подождите немного...",
        "menu_referat": "📄 Создать реферат",
        "menu_presentation": "📊 Презентация",
        "payment_manual": "Оплатите выбранную сумму на следующую пластиковую карту через любую платёжную систему.\n\n-Karta raqami: 9860340103696845\n-Karta egasi: Azamjon Roziboyev\n\nЗатем отправьте скриншот или PDF чека о платеже.\n\nОжидайте подтверждения оплаты. Этот процесс может занять около 5 минут.",
        "menu_word": "📝 Создать Word файл",
        "menu_word_save": "💾 Сохранить",
        "menu_back": "⬅️ Назад",
        "menu_help": "ℹ️ Помощь",
        "menu_tezis": "✍️ Написать тезис",
        "menu_mustaqil": "📜 Написать самостоятельную работу",
        "balance_info": "Вот ваш баланс:",
        "menu_balance": "💰Баланс",
        "mustaqil_ishi_titul": "Самостоятельная работа",
        "Referat_titul": "РЕФЕРАТ",
        "bajaruvchi_titul": "Выполнил(а):",
        "qabul_qiluvchi_titul": "Принял(а):",
        "xulosa_titul": "Заключение",
        "adabiyotlar_titul": "Использованная литература",
        "mavzu_titul": "Тема",
        "reja_titul": "ПЛАН:",
        #referat yozish
        "university_referat": "Universitetingizni kiriting:",
        "student_referat": "Введите имя студента:",
        "language_referat": "На каком языке будет реферат:",
        "teacher_referat": "Введите приемника:",
        "topic_referat": "Тема:",
        "pages_referat": "Сколько страниц должен быть реферат?",
        "referat_generating": "Ваш реферат готовится, пожалуйста, подождите немного...",
        "language_mustaqil": "На каком языке будет самостоятельная работа: ",
        "alerta_payment": "❌ У вас нет бесплатных попыток создать презентацию, и недостаточно средств на балансе.💳 Пожалуйста, пополните ваш баланс",
        "menu_referal": "🆓 Бесплатное создание",
        "menu_prices": "🏷️ Цены",
        "make_payment": "Пополнить баланс 💲",
        "choose_amount": "На какую сумму вы хотите пополнить свой счёт?\n\nПожалуйста, выберите одну из сумм ниже",
        "send_receipt": "📸 Пожалуйста, отправьте фото или PDF-файл квитанции об оплате: \n\nУбедитесь, что на квитанции указано время совершения платежа!\n\n Квитанции без указания времени оплаты не принимаются!",
        "welcome": "👋 Добро пожаловать!\n\nЗапустив бота, вы получили следующие бесплатные попытки:\n\n📄 Создание реферата — 2 бесплатные попытки\n📊 Создание презентации — 2 бесплатные попытки\n📝 Подготовка тезисов — 2 бесплатные попытки\n📚 Создание самостоятельной работы — 2 бесплатные попытки\n\nКаждой услугой можно воспользоваться бесплатно.\nПосле окончания бесплатных попыток для использования услуг потребуется баланс 💰\n\n📌 Кроме того, вы можете пополнять баланс, приглашая друзей в бот.\nДля этого перейдите в меню 🆓 Бесплатное создание.",
        "policy_confirmation": "\n📌 Обратите внимание: используя бота, вы соглашаетесь с политикой конфиденциальности.\nОзнакомьтесь с политикой конфиденциальности по ссылке ниже:\nhttps://telegra.ph/Politika-konfidencialnosti-12-19-19",
        "referal_payment": "🎉 Ваш реферал запустил бота!\n+1000 сум добавлено на ваш баланс 💰",
        "help_menu_text": "ℹ️ Помощь\n🤖 Этот бот помогает быстро создавать учебные работы.\n📝 С помощью меню создания файла Word вы можете вставлять любой текст и изображения в файл Word. Созданный файл будет сохранён в формате .docx.\n📄 Реферат — автоматическое создание реферата по теме с выбором языка и объема.\n📊 Презентация — создание презентации в виде слайдов с выбором темы и количества слайдов.\n🧾 Тезисы — генерация кратких научных тезисов для учебных и конференционных работ.\n📝 Самостоятельная работа — подготовка самостоятельной работы с выбором темы и объема.\n💰 Баланс — просмотр баланса и оставшихся бесплатных попыток.\n🎁 Бесплатные попытки — приглашайте друзей и получайте бесплатные попытки.\n⚙️ Настройки — изменение языка и параметров бота.\n📩 Контакты — связь с администратором по вопросам и проблемам.\n📌 Примечание: используйте бота только через меню.",
        "payment_sent": "Чек успешно отправлен.\nПосле подтверждения правильности оплаты ваш баланс будет пополнен. Это может занять до 5 минут.\nПроверьте ваш баланс через меню 💰Баланс.",
        "text_prices": "💰 Цены на услуги\n📊 Создание презентации — 3 000 сум\n📄 Написание реферата — 2 000 сум\n📘 Подготовка самостоятельной работы — 2 000 сум\n📝 Написание тезисов — 3 000 сум\n\n💳 Оплата производится через баланс.\nℹ️ При недостаточном балансе услуга недоступна.",
        "payment_confirmed": "✅ Ваш платеж подтверждён.\nСумма платежа:",
        "payment_rejected": "❌ Ваш платеж в размере  отклонен.",
        "payment_auto_refund": "✅ Ваш платеж подтверждён."

    },
    "eng": {
        "start": "Hello! What shall we do?",
        "university_mustaqil": "Enter your university:",
        "student_mustaqil": "Enter student name:",
        "teacher_mustaqil": "Enter supervisor:",
        "topic_mustaqil": "Topic:",
        "student_tezis": "Enter the writer's full name.",
        "language_tezis": "Which language should the thesis be: ",
        "pages_mustaqil": "How many pages should the report have?",
        "caption_file": "Ready!\nThe system may make mistakes, please check important information.",

        "language_mustaqil": "Which language should the independent work be: ",
        "mustaaqil_generating": "Your independent work is being prepared, please wait a moment...",
        "language": "Select language:",
        "caption_mustaqil": "This is your independent work. Please take a look. \n @slayd_chibot - создатель слайдов и рефератов!",
        #menu buttons        
        "menu_alert": "Please use the bot through the menu", #echo handler
        "alert_upcoming": "This section will start working soon.",
        "tezis_generating":"Your thesis is being prepared, please wait a moment..",
        "menu_referat": "📄 Create Referat",
        "menu_presentation": "📊 Presentation",
        "menu_word": "📝 Create Word File",
        "menu_help": "ℹ️ Help",
        "menu_word_save": "💾 Save",
        "menu_tezis": "✍️ Write Thesis",
        "menu_mustaqil": "📜 Write Independent Work",
        "menu_back": "⬅️ Back",
        "balance_info": "Here is your balance:",
        "menu_balance": "💰Balance",
        "mustaqil_ishi_titul": "Independent Work",
        "Referat_titul": "РЕФЕРАТ",
        "bajaruvchi_titul": "Done by:",
        "qabul_qiluvchi_titul": "Accepted by:",
        "xulosa_titul": "Conclusion",
        "adabiyotlar_titul": "References",
        "payment_manual": "Transfer your chosen amount to the following plastic card via any payment system.\n\n-Karta raqami: 9860340103696845\n-Karta egasi: Azamjon Roziboyev\n\nThen send a screenshot or PDF of the payment receipt.\nPlease wait for your payment to be confirmed. This process may take around 5 minutes.",
        "mavzu_titul": "Topic",
        "reja_titul": "PLAN:",

        #referat yozish
        "university_referat": "Universitetingizni kiriting:",
        "student_referat": "Enter your name:",
        "language_referat": "Which language should the report be:",
        "teacher_referat": "Enter the supervisor:",
        "topic_referat": "Topic:",
        "pages_referat": "How many pages should the report have?",
        "referat_generating": "Your report is being prepared, please wait a moment...",
        "alerta_payment": "❌ You have no free presentation attempts and insufficient balance.💳 Please top up your balance.",
        "menu_referal": "🆓 Free creation",
        "menu_prices": "🏷️ Prices",
        "make_payment": "Top up balance 💲",
        "choose_amount": "How much would you like to top up your account?\n\nPlease select one of the amounts below:",
        "send_receipt": "📸 Please send a photo or PDF of your payment receipt: \n\n Please make sure the payment time is visible on the receipt!\n\n Receipts without a visible payment time will not be accepted!",
        "welcome": "👋 Welcome!\n\nBy starting the bot, you have received the following free attempts:\n\n📄 Essay creation — 2 free attempts\n📊 Presentation creation — 2 free attempts\n📝 Thesis preparation — 2 free attempts\n📚 Independent work creation — 2 free attempts\n\nEach service can be used for free.\nAfter the free attempts are used up, a balance will be required to continue using the services 💰\n\n📌 In addition, you can increase your balance by inviting friends to the bot.\nTo do this, go to the 🆓 Free creation menu.",
        "policy_confirmation": "\n📌 Please note: by using this bot, you agree to the privacy policy.\nYou can review the privacy policy using the link below:\nhttps://telegra.ph/Politika-konfidencialnosti-12-19-19",
        "referal_payment": "🎉 Your referral has started the bot!\n+1000 UZS has been added to your balance 💰",
        "help_menu_text": "ℹ️ Help\n🤖 This bot helps you quickly generate academic works.\n📝 Using the Word file creation menu, you can insert any text and images into a Word file. The created file will be saved in .docx format.\n📄 Referat — automatically creates a referat based on the topic with language and length selection.\n📊 Presentation — creates a slide-based presentation with topic and slide count selection.\n🧾 Tezis — generates scientific theses or a short summary.\n📝 Mustaqil work — prepares independent student work with topic and length selection.\n💰 Balance — shows your balance and remaining free attempts.\n🎁 Free attempts — invite friends and get free attempts.\n⚙️ Settings — change the language and manage bot settings.\n📩 Contact — contact the administrator for questions or issues.\n📌 Note: please use the bot only through the menu.",
        "payment_sent": "Receipt successfully sent.\nYour balance will be updated once the payment is confirmed. This may take up to 5 minutes.\nCheck your balance via 💰Balance menu.",
        "text_prices": "💰 Service prices\n📊 Presentation creation — 3,000 UZS\n📄 Essay writing — 2,000 UZS\n📘 Independent work preparation — 2,000 UZS\n📝 Thesis writing — 3,000 UZS\n\n💳 Payment is made via balance.\nℹ️ If the balance is insufficient, the service cannot be used.",
        "payment_confirmed": "✅ Your payment has been confirmed.\nPayment amount:",
        "payment_rejected": "❌ Your payment was rejected.",
        "payment_auto_refund": "✅ Your payment has been confirmed."
        
        
    }
}
